# Author: Sébastien Combéfis
# Version: November 27, 2016

def options(opt):
    opt.load('compiler_c')

def configure(cnf):
    cnf.load('compiler_c')

def build(bld):
    bld.program(source='src/utils.c src/computer.c', target='computer', cflags='-I. -O2 -pedantic -pipe -std=c99 -Wall -Werror')
